import type { CategoriaAnimale } from '@/lib/types/app.types'

export const SUGGERIMENTI_ANIMALE_PER_CATEGORIA: Record<CategoriaAnimale, string[]> = {
  cani: [
    'Jack Russell',
    'Jack Russell Terrier',
    'Parson Russell Terrier',
    'Labrador',
    'Labrador Retriever',
    'Golden Retriever',
    'Pastore Tedesco',
    'Pastore Belga',
    'Border Collie',
    'Australian Shepherd',
    'Bulldog Francese',
    'Bulldog Inglese',
    'Carlino',
    'Barboncino',
    'Barboncino Toy',
    'Barboncino Nano',
    'Barboncino Medio',
    'Barboncino Standard',
    'Maltese',
    'Yorkshire Terrier',
    'Chihuahua',
    'Beagle',
    'Boxer',
    'Rottweiler',
    'Dobermann',
    'Cane Corso',
    'Pinscher',
    'Volpino Italiano',
    'Spitz',
    'Spitz Tedesco',
    'Shih Tzu',
    'Cocker Spaniel',
    'Cocker Spaniel Inglese',
    'Cocker Spaniel Americano',
    'Bassotto',
    'Bassotto pelo corto',
    'Bassotto pelo lungo',
    'Bassotto pelo duro',
    'Setter Inglese',
    'Setter Irlandese',
    'Bracco Italiano',
    'Pointer Inglese',
    'Weimaraner',
    'Dalmata',
    'Akita Inu',
    'Shiba Inu',
    'Husky',
    'Husky Siberiano',
    'Alaskan Malamute',
    'Samoiedo',
    'Terranova',
    'Bovaro del Bernese',
    'Bernese',
    'San Bernardo',
    'Alano',
    'Lagotto Romagnolo',
    'Segugio Italiano',
    'Spinone Italiano',
    'Boston Terrier',
    'Bull Terrier',
    'Staffordshire Bull Terrier',
    'American Staffordshire Terrier',
    'Pitbull',
    'Rhodesian Ridgeback',
    'Cavalier King Charles Spaniel',
    'Bichon Frisé',
    'Bouledogue Francese',
    'Meticcio',
  ],

  gatti: [
    'Europeo',
    'Europeo Comune',
    'Persiano',
    'Persiano Chinchilla',
    'Maine Coon',
    'Siamese',
    'Thai',
    'Bengala',
    'Ragdoll',
    'British Shorthair',
    'British Longhair',
    'Abissino',
    'Sphynx',
    'Certosino',
    'Sacro di Birmania',
    'Norvegese delle Foreste',
    'Siberiano',
    'Angora Turco',
    'Russian Blue',
    'Burmese',
    'Devon Rex',
    'Cornish Rex',
    'Scottish Fold',
    'Scottish Straight',
    'Orientale',
    'Exotic Shorthair',
    'Ocicat',
    'Tonkinese',
    'Bombay',
    'Somalo',
    'Turkish Van',
    'Manx',
    'Kurilian Bobtail',
    'American Curl',
    'Selkirk Rex',
    'Meticcio',
  ],

  pesci: [
    'Pesce Rosso',
    'Carassius',
    'Betta',
    'Guppy',
    'Neon Tetra',
    'Cardinale',
    'Scalare',
    'Discus',
    'Molly',
    'Platy',
    'Portaspada',
    'Corydoras',
    'Pleco',
    'Ancistrus',
    'Danio',
    'Barbo',
    'Rasbora',
    'Koi',
    'Pesce Palla',
    'Arowana',
    'Ciclide Africano',
    'Ramirezi',
    'Apistogramma',
  ],

  uccelli: [
    'Cocorita',
    'Canarino',
    'Calopsita',
    'Ara',
    'Cacatua',
    'Amazzone',
    'Pappagallo Grigio Africano',
    'Inseparabile',
    'Rosella',
    'Parrocchetto Monaco',
    'Parrocchetto dal collare',
    'Diamante Mandarino',
    'Diamante di Gould',
    'Fringuello',
    'Cardellino',
    'Verdone',
    'Pappagallino ondulato',
    'Ecletto',
    'Lorichetto',
  ],

  rettili: [
    'Geco Leopardino',
    'Geco Crestato',
    'Geco Gargoyle',
    'Drago Barbuto',
    'Iguana Verde',
    'Camaleonte Velato',
    'Camaleonte Panther',
    'Serpente del Grano',
    'Pitone Reale',
    'Boa Constrictor',
    'Serpente Re della California',
    'Tartaruga di Terra',
    'Tartaruga Acquatica',
    'Trachemys',
    'Testuggine di Hermann',
    'Anolis',
    'Scinco',
    'Uromastice',
  ],

  piccoli_mammiferi: [
    'Coniglio Nano',
    'Coniglio Ariete',
    'Coniglio Testa di Leone',
    'Coniglio Rex',
    'Coniglio Nano Olandese',
    'Criceto Dorato',
    'Criceto Nano',
    'Criceto Russo',
    'Criceto Roborowski',
    'Cavia',
    'Cavia Peruviana',
    'Cavia Americana',
    'Cavia Sheltie',
    'Cincillà',
    'Furetto',
    'Gerbillo',
    'Degu',
    'Topo Domestico',
    'Ratto Domestico',
    'Scoiattolo',
    'Riccio africano',
    'Meticcio',
  ],

  altri_animali: [
    'Axolotl',
    'Raganella',
    'Rana',
    'Tarantola',
    'Scorpione',
    'Lumaca Gigante Africana',
    'Granchio Eremita',
    'Riccio di Mare',
    'Granchio',
    'Gambero d acqua dolce',
  ],
}