import type { CategoriaAnimale } from '@/lib/types/app.types'

export const SUGGERIMENTI_ANIMALE_PER_CATEGORIA: Record<CategoriaAnimale, string[]> = {
  cani: [
    'Labrador Retriever',
    'Pastore Tedesco',
    'Golden Retriever',
    'Bulldog Francese',
    'Barboncino',
    'Beagle',
    'Boxer',
    'Chihuahua',
    'Husky Siberiano',
    'Shih Tzu',
    'Maltese',
    'Yorkshire Terrier',
    'Carlino',
    'Dobermann',
    'Rottweiler',
    'Cocker Spaniel',
    'Dalmata',
    'Setter Irlandese',
    'Alano',
    'Bassotto',
    'Border Collie',
    'Cane Corso',
    'Lagotto Romagnolo',
    'Bracco Italiano',
    'Segugio Italiano',
    'Spinone Italiano',
    'Volpino Italiano',
    'Meticcio',
  ],
  gatti: [
    'Europeo Comune',
    'Persiano',
    'Maine Coon',
    'Siamese',
    'Bengala',
    'Ragdoll',
    'British Shorthair',
    'Abissino',
    'Sphynx',
    'Certosino',
    'Sacro di Birmania',
    'Norvegese delle Foreste',
    'Siberiano',
    'Angora Turco',
    'Russian Blue',
    'Burmese',
    'Devon Rex',
    'Cornish Rex',
    'Scottish Fold',
    'Ocicat',
    'Tonkinese',
    'Meticcio',
  ],
  pesci: [
    'Pesce Rosso',
    'Carassius',
    'Betta',
    'Guppy',
    'Neon Tetra',
    'Ciclide Africano',
    'Discus',
    'Scalare',
    'Molly',
    'Platy',
    'Corydoras',
    'Pleco',
    'Koi',
    'Danio',
    'Barbo',
    'Rasbora',
    'Pesce Palla',
    'Arowana',
  ],
  uccelli: [
    'Cocorita',
    'Canarino',
    'Pappagallo Grigio Africano',
    'Cacatua',
    'Ara',
    'Amazzone',
    'Calopsita',
    'Rosella',
    'Fringuello',
    'Cardellino',
    'Verdone',
    'Diamante Mandarino',
  ],
  rettili: [
    'Geco Leopardino',
    'Drago Barbuto',
    'Iguana Verde',
    'Camaleonte Velato',
    'Serpente del Grano',
    'Boa Constrictor',
    'Pitone Reale',
    'Tartaruga di Terra',
    'Tartaruga Acquatica',
    'Anolis',
    'Geco Crestato',
  ],
  piccoli_mammiferi: [
    'Criceto Dorato',
    'Criceto Nano',
    'Coniglio Nano',
    'Coniglio Ariete',
    'Coniglio Rex',
    'Cavia',
    'Cincillà',
    'Ratto Domestico',
    'Topo Domestico',
    'Gerbillo',
    'Furetto',
    'Degu',
    'Meticcio',
  ],
  altri_animali: [
    'Axolotl',
    'Raganella',
    'Tarantola',
    'Scorpione',
    'Lumaca Gigante Africana',
    'Granchio Eremita',
    'Riccio di Mare',
  ],
}